dev:
    cargo watch -w src -x run | bunyan

build:
    cargo build --release

fmt:
    cargo +nightly fmt

test:
    cargo nextest run

test_ci:
    cargo nextest run --no-fail-fast

udeps:
    cargo +nightly udeps --all-targets

update_geo:
    docker compose -f geo/docker-compose.yaml up
