dev:
    cargo watch -w src -x run

fmt:
    cargo +nightly fmt

udeps:
    cargo +nightly udeps --all-targets

fmt_sql:
    ./bin/format-sql.sh

update_geo:
    docker-compose -f geo/docker-compose.yaml up
