import { isDarwin } from "@storiny/shared/src/browsers";

export enum KeyCode {
  BRACKET_LEFT = "BracketLeft",
  BRACKET_RIGHT = "BracketRight",
  C = "KeyC",
  D = "KeyD",
  EQUAL = "Equal",
  H = "KeyH",
  MINUS = "Minus",
  NINE = "Digit9",
  NUM_ADD = "NumpadAdd",
  NUM_SUBTRACT = "NumpadSubtract",
  NUM_ZERO = "Numpad0",
  ONE = "Digit1",
  QUOTE = "Quote",
  R = "KeyR",
  SLASH = "Slash",
  THREE = "Digit3",
  TWO = "Digit2",
  V = "KeyV",
  Z = "KeyZ",
  ZERO = "Digit0"
}

export const KEYS = {
  ARROW_DOWN: "ArrowDown",
  ARROW_LEFT: "ArrowLeft",
  ARROW_RIGHT: "ArrowRight",
  ARROW_UP: "ArrowUp",
  PAGE_UP: "PageUp",
  PAGE_DOWN: "PageDown",
  BACKSPACE: "Backspace",
  ALT: "Alt",
  CTRL_OR_CMD: isDarwin ? "metaKey" : "ctrlKey",
  DELETE: "Delete",
  ENTER: "Enter",
  ESCAPE: "Escape",
  QUESTION_MARK: "?",
  SPACE: " ",
  TAB: "Tab",
  CHEVRON_LEFT: "<",
  CHEVRON_RIGHT: ">",
  PERIOD: ".",
  COMMA: ",",
  SUBTRACT: "-",
  //
  A: "a",
  C: "c",
  D: "d",
  E: "e",
  F: "f",
  G: "g",
  H: "h",
  I: "i",
  L: "l",
  O: "o",
  P: "p",
  Q: "q",
  R: "r",
  S: "s",
  T: "t",
  V: "v",
  X: "x",
  Y: "y",
  Z: "z",
  K: "k",
  //
  0: "0",
  1: "1",
  2: "2",
  3: "3",
  4: "4",
  5: "5",
  6: "6",
  7: "7",
  8: "8",
  9: "9"
} as const;

export type Key = keyof typeof KEYS;
