import { StoryCategory } from "@storiny/shared";
import { nanoid } from "nanoid";

const { worker, rest } = window.msw;

const mockData = {
  [StoryCategory.PROGRAMMING]: [
    "rust",
    "wasm",
    "javascript",
    "typescript",
    "perl",
    "vue",
    "react",
    "angular",
    "go-lang",
    "data-science",
    "databases",
    "nodejs",
    "python",
    "ruby-on-rails",
    "java",
    "c-sharp",
    "swift",
    "php",
    "android-dev",
    "ios-dev",
    "cloud-computing",
    "machine-learning",
    "artificial-intelligence",
    "game-development",
  ].map((tag) => ({ name: tag, id: nanoid() })),
  [StoryCategory.DIY]: [
    "rc-turbines",
    "home-decor",
    "origami",
    "wallpaper",
    "rc-model",
    "furniture",
    "knitting",
    "embroidery",
    "tech-gadgets",
    "woodworking",
    "paper-crafts",
    "jewelry-making",
    "candle-making",
    "leatherworking",
    "metalworking",
    "gardening-tools",
    "sewing-patterns",
    "pottery",
    "ceramics",
    "quilting",
    "scrapbooking",
    "beading",
    "soap-making",
    "candle-holders",
    "painting-supplies",
  ].map((tag) => ({ name: tag, id: nanoid() })),
  [StoryCategory.GAMING]: [
    "minecraft",
    "fortnite",
    "valorant",
    "hades",
    "apex-legends",
    "cyberpunk-2077",
    "doom-eternal",
    "overwatch",
    "rocket-league",
    "league-of-legends",
    "pubg",
    "rainbow-six-siege",
    "the-elder-scrolls",
    "counter-strike",
    "red-dead-redemption",
    "fallout",
    "destiny",
    "battlefield",
    "resident-evil",
    "dark-souls",
    "god-of-war",
    "borderlands",
    "uncharted",
    "dead-by-daylight",
    "final-fantasy",
  ].map((tag) => ({ name: tag, id: nanoid() })),
};

worker.use(
  rest.get(
    `${process.env.NEXT_PUBLIC_API_URL}/v1/me/flow/onboarding/tags`,
    (req, res, ctx) => res(ctx.delay(1200), ctx.json(mockData))
  )
);

export {};
