CREATE TABLE IF NOT EXISTS story_tags(
    story_id BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (story_id, tag_id)
);

